apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: sample
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: juuni.kim@cloudmt.co.kr
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
