apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sample

commonLabels:
  app: sample

resources:
- namespace.yaml
- issuer.yaml
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- ingress-active.yaml
- ingress-preview.yaml
