apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sample

commonLabels:
  app: sample

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- issuer.yaml
- ingress.yaml
