apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: acm-demo
spec:
  selector:
    app: hello-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer